x = int(input("Give me the first number: "))
y = int(input("Give me the second number: "))
print("Thank you!")
print(str(x) + " + " + str(y) + " = " + str(x + y))
print(str(x) + " - " + str(y) + " = " + str(x - y))
print(str(x) + " * " + str(y) + " = " + str(x * y))
print(str(x) + " / " + str(y) + " = " + str(round(x / y)))
